# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfoodie', '0009_auto_20160808_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='idPro',
            new_name='idRest',
        ),
    ]
