# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfoodie', '0015_auto_20160810_0315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='idPro',
            new_name='idPedi',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='idRes',
            new_name='idPro',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='idCli',
        ),
        migrations.AddField(
            model_name='pedido',
            name='Cliente',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
