# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 14:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appfoodie', '0019_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Imagen',
            field=models.ImageField(default=datetime.datetime(2016, 8, 10, 14, 31, 32, 321598, tzinfo=utc), upload_to='static'),
            preserve_default=False,
        ),
    ]
