# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfoodie', '0020_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Imagen',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
