# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfoodie', '0022_userprofile_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Nombre',
        ),
    ]
