# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 05:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appfoodie', '0026_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Apellidos',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='CI',
            field=models.CharField(default=datetime.datetime(2016, 8, 12, 5, 44, 51, 959973, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Direccion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Email',
            field=models.EmailField(default=datetime.datetime(2016, 8, 12, 5, 45, 10, 465315, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Nombres',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Telefono',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
